# Site settings
author: Michelle Olivieri
title: Coding with Mich
header-img: img/home-bg.png
email: michelleo72@gmail.com
copyright_name: Michelle Olivieri
description: > # this means to ignore newlines until "baseurl:"
  My Journey from Advertising to Coding

baseurl: "" # the subpath of your site, e.g. /blog
url: http://localhost:4000
twitter_username:
github_username:  micholi

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
