# Site settings
title: Coding with Mich
header-img: img/home-bg.png
email: michelleo72@gmail.com
copyright_name: micholi
description: > # this means to ignore newlines until "baseurl:"
  My Journey from Advertising to Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  micholi
learn_profile: micholi
email_username: michelleo72@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
